variable vpc_id {}
variable subnet_id {}
variable availability_zone {}
variable env_prefix {}
variable image_name {}
variable instance_type {}
variable my_ip {}
variable public_key_location {}
variable private_key_location {}